# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nanocodex/v1/mcpv8.proto, nanocodex/v1/operations.proto, nanocodex/v1/sandbox.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class EvalMode(betterproto.Enum):
    UNSPECIFIED = 0
    ALL = 1
    ANY = 2


class ConfigFormat(betterproto.Enum):
    UNSPECIFIED = 0
    TOML = 1
    JSON = 2


class TurnStatus(betterproto.Enum):
    UNSPECIFIED = 0
    COMPLETED = 1
    INTERRUPTED = 2
    FAILED = 3
    IN_PROGRESS = 4


@dataclass(eq=False, repr=False)
class McpV8Config(betterproto.Message):
    """
    Top-level mcp-v8 config. Only a subset of scalar flags is modeled explicitly;
     everything mcp-v8 accepts is expressible, and unmodeled scalar flags can be
     carried in `extra` (merged as top-level keys when serialized).
    """

    policies: "Policies" = betterproto.message_field(1)
    """Structured sections."""

    fetch_headers: List["FetchHeaderRule"] = betterproto.message_field(2)
    mcp_servers: List["McpServer"] = betterproto.message_field(3)
    wasm: Dict[str, "WasmModule"] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    http_port: Optional[int] = betterproto.uint32_field(10, optional=True)
    """
    Common scalar flags (snake_case mirrors the CLI; 0/empty means "unset").
    """

    sse_port: Optional[int] = betterproto.uint32_field(11, optional=True)
    bind_host: Optional[str] = betterproto.string_field(12, optional=True)
    heap_memory_max: Optional[int] = betterproto.uint64_field(13, optional=True)
    execution_timeout: Optional[int] = betterproto.uint64_field(14, optional=True)
    max_concurrent_executions: Optional[int] = betterproto.uint32_field(
        15, optional=True
    )
    heap_store: Optional[str] = betterproto.string_field(16, optional=True)
    heap_dir: Optional[str] = betterproto.string_field(17, optional=True)
    fs_store: Optional[str] = betterproto.string_field(18, optional=True)
    fs_dir: Optional[str] = betterproto.string_field(19, optional=True)
    extra: Dict[str, str] = betterproto.map_field(
        100, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """
    Escape hatch for scalar flags not modeled above; merged as top-level keys.
    """


@dataclass(eq=False, repr=False)
class Policies(betterproto.Message):
    """
    The `policies` object: a per-operation policy chain keyed by operation.
    """

    fetch: "OperationPolicies" = betterproto.message_field(1)
    modules: "OperationPolicies" = betterproto.message_field(2)
    filesystem: "OperationPolicies" = betterproto.message_field(3)
    fs_snapshot: "OperationPolicies" = betterproto.message_field(4)
    mcp_tools: "OperationPolicies" = betterproto.message_field(5)
    subprocess: "OperationPolicies" = betterproto.message_field(6)
    run_js_file: "OperationPolicies" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class OperationPolicies(betterproto.Message):
    mode: "EvalMode" = betterproto.enum_field(1)
    policies: List["PolicySource"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class PolicySource(betterproto.Message):
    url: str = betterproto.string_field(1)
    policy_path: Optional[str] = betterproto.string_field(2, optional=True)
    rule: Optional[str] = betterproto.string_field(3, optional=True)


@dataclass(eq=False, repr=False)
class FetchHeaderRule(betterproto.Message):
    """
    One fetch header rule: exactly one of `headers` (static) or `auth` (OAuth
     client-credentials) is set.
    """

    host: str = betterproto.string_field(1)
    methods: List[str] = betterproto.string_field(2)
    headers: "StaticHeaders" = betterproto.message_field(3, group="injection")
    auth: "OAuthClientCredentials" = betterproto.message_field(4, group="injection")


@dataclass(eq=False, repr=False)
class StaticHeaders(betterproto.Message):
    headers: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OAuthClientCredentials(betterproto.Message):
    type: str = betterproto.string_field(1)
    """
    JSON tag is "oauth_client_credentials"; carried as a constant on the wire.
    """

    header: str = betterproto.string_field(2)
    token_url: str = betterproto.string_field(3)
    client_id: str = betterproto.string_field(4)
    client_secret: str = betterproto.string_field(5)
    scope: Optional[str] = betterproto.string_field(6, optional=True)
    refresh_buffer_secs: Optional[int] = betterproto.uint64_field(7, optional=True)


@dataclass(eq=False, repr=False)
class McpServer(betterproto.Message):
    name: str = betterproto.string_field(1)
    stdio: "StdioTransport" = betterproto.message_field(2, group="transport")
    sse_url: str = betterproto.string_field(3, group="transport")


@dataclass(eq=False, repr=False)
class StdioTransport(betterproto.Message):
    command: str = betterproto.string_field(1)
    args: List[str] = betterproto.string_field(2)
    env: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WasmModule(betterproto.Message):
    path: str = betterproto.string_field(1)
    max_memory_bytes: Optional[int] = betterproto.uint64_field(2, optional=True)
    description: Optional[str] = betterproto.string_field(3, optional=True)


@dataclass(eq=False, repr=False)
class SandboxSpec(betterproto.Message):
    config: Optional["McpV8Config"] = betterproto.message_field(1, optional=True)
    """
    Preferred: one mcp-v8 config document. Written to the container fs and
     passed as `--config <path>`. When set, owns the mcp-v8 configuration.
    """

    config_format: "ConfigFormat" = betterproto.enum_field(2)
    raw: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(3)
    """
    Escape hatch: entire `mcp_servers.js` value, used verbatim (ignores all
     other fields). google.protobuf.Struct = arbitrary JSON object.
    """

    args: List[str] = betterproto.string_field(4)
    """Raw mcp-v8 argv; empty => a sensible default (--policies-json)."""

    env: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """Extra environment for the mcp-v8 process."""

    files: Dict[str, str] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """
    {container_path: content} written to the container fs BEFORE mcp-v8 starts
     (via an `sh -c` wrapper). The mechanism for shipping custom rego.
    """

    policies_inline: Optional["McpV8Config"] = betterproto.message_field(
        7, optional=True
    )
    """
    Conveniences (used only when `config`/`raw`/`args` are unset, except
     `bearer`, which also folds into a `config`'s fetch_headers).
    """

    bearer: List["Bearer"] = betterproto.message_field(8)
    oauth_rules: List[str] = betterproto.string_field(9)
    extra_args: List[str] = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class Bearer(betterproto.Message):
    host: str = betterproto.string_field(1)
    token: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class CreateThreadRequest(betterproto.Message):
    model: Optional[str] = betterproto.string_field(1, optional=True)
    sandbox: "SandboxSpec" = betterproto.message_field(2)
    cwd: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CreateThreadResponse(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    model: str = betterproto.string_field(2)
    model_provider: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class StartTurnRequest(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    prompt: str = betterproto.string_field(2)
    timeout_secs: float = betterproto.double_field(3)
    sandbox: "SandboxSpec" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class SteerRequest(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    prompt: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MessagesRequest(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    verbose: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ListThreadsRequest(betterproto.Message):
    limit: int = betterproto.uint32_field(1)
    cursor: Optional[str] = betterproto.string_field(2, optional=True)


@dataclass(eq=False, repr=False)
class RpcRequest(betterproto.Message):
    method: str = betterproto.string_field(1)
    params: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class RpcResponse(betterproto.Message):
    result: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ToolCall(betterproto.Message):
    tool: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    output: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TurnResult(betterproto.Message):
    """
    Result of run_turn: the turn outcome plus what we collected while streaming.
    """

    status: "TurnStatus" = betterproto.enum_field(1)
    agent_messages: List[str] = betterproto.string_field(2)
    tool_calls: List["ToolCall"] = betterproto.message_field(3)
    turn: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(4)
    """The raw codex Turn payload, passed through untyped."""


@dataclass(eq=False, repr=False)
class TranscriptItem(betterproto.Message):
    """One line of a rendered transcript item."""

    kind: str = betterproto.string_field(1)
    text: str = betterproto.string_field(2)
    item: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TranscriptTurn(betterproto.Message):
    turn_id: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    items: List["TranscriptItem"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class Transcript(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    turns: List["TranscriptTurn"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ThreadSummary(betterproto.Message):
    thread_id: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    preview: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ListThreadsResponse(betterproto.Message):
    threads: List["ThreadSummary"] = betterproto.message_field(1)


class NanocodexServiceStub(betterproto.ServiceStub):
    async def create_thread(
        self,
        create_thread_request: "CreateThreadRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CreateThreadResponse":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/CreateThread",
            create_thread_request,
            CreateThreadResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_turn(
        self,
        start_turn_request: "StartTurnRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "TurnResult":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/StartTurn",
            start_turn_request,
            TurnResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def steer(
        self,
        steer_request: "SteerRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "betterproto_lib_google_protobuf.Struct":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/Steer",
            steer_request,
            betterproto_lib_google_protobuf.Struct,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def messages(
        self,
        messages_request: "MessagesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Transcript":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/Messages",
            messages_request,
            Transcript,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_threads(
        self,
        list_threads_request: "ListThreadsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListThreadsResponse":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/ListThreads",
            list_threads_request,
            ListThreadsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def rpc(
        self,
        rpc_request: "RpcRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RpcResponse":
        return await self._unary_unary(
            "/nanocodex.v1.NanocodexService/Rpc",
            rpc_request,
            RpcResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class NanocodexServiceBase(ServiceBase):

    async def create_thread(
        self, create_thread_request: "CreateThreadRequest"
    ) -> "CreateThreadResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def start_turn(self, start_turn_request: "StartTurnRequest") -> "TurnResult":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def steer(
        self, steer_request: "SteerRequest"
    ) -> "betterproto_lib_google_protobuf.Struct":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def messages(self, messages_request: "MessagesRequest") -> "Transcript":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_threads(
        self, list_threads_request: "ListThreadsRequest"
    ) -> "ListThreadsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def rpc(self, rpc_request: "RpcRequest") -> "RpcResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_create_thread(
        self, stream: "grpclib.server.Stream[CreateThreadRequest, CreateThreadResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.create_thread(request)
        await stream.send_message(response)

    async def __rpc_start_turn(
        self, stream: "grpclib.server.Stream[StartTurnRequest, TurnResult]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.start_turn(request)
        await stream.send_message(response)

    async def __rpc_steer(
        self,
        stream: "grpclib.server.Stream[SteerRequest, betterproto_lib_google_protobuf.Struct]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.steer(request)
        await stream.send_message(response)

    async def __rpc_messages(
        self, stream: "grpclib.server.Stream[MessagesRequest, Transcript]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.messages(request)
        await stream.send_message(response)

    async def __rpc_list_threads(
        self, stream: "grpclib.server.Stream[ListThreadsRequest, ListThreadsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_threads(request)
        await stream.send_message(response)

    async def __rpc_rpc(
        self, stream: "grpclib.server.Stream[RpcRequest, RpcResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.rpc(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nanocodex.v1.NanocodexService/CreateThread": grpclib.const.Handler(
                self.__rpc_create_thread,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateThreadRequest,
                CreateThreadResponse,
            ),
            "/nanocodex.v1.NanocodexService/StartTurn": grpclib.const.Handler(
                self.__rpc_start_turn,
                grpclib.const.Cardinality.UNARY_UNARY,
                StartTurnRequest,
                TurnResult,
            ),
            "/nanocodex.v1.NanocodexService/Steer": grpclib.const.Handler(
                self.__rpc_steer,
                grpclib.const.Cardinality.UNARY_UNARY,
                SteerRequest,
                betterproto_lib_google_protobuf.Struct,
            ),
            "/nanocodex.v1.NanocodexService/Messages": grpclib.const.Handler(
                self.__rpc_messages,
                grpclib.const.Cardinality.UNARY_UNARY,
                MessagesRequest,
                Transcript,
            ),
            "/nanocodex.v1.NanocodexService/ListThreads": grpclib.const.Handler(
                self.__rpc_list_threads,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListThreadsRequest,
                ListThreadsResponse,
            ),
            "/nanocodex.v1.NanocodexService/Rpc": grpclib.const.Handler(
                self.__rpc_rpc,
                grpclib.const.Cardinality.UNARY_UNARY,
                RpcRequest,
                RpcResponse,
            ),
        }
